version: "3.3"
services:
  nginx:
    image: nginx:1.15
    container_name: json-validator-nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      base_net:
        ipv4_address: 172.18.241.4

  php:
    build: ./docker/php/
    container_name: json-validator-php
    image: jsonvalidator_php
    ports:
      - 9000
    volumes:
      # File to override PHP configuration dynamically.
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/30-local.ini
      - ./:/var/www/html
      - /tmp:/tmp
      - ${COMPOSER_CACHE}:/.composer/cache
    depends_on:
      - mysql
    # Make sure `uid` is available in env.
    user: ${uid}:${gid}
    environment:
    # Workaround for pre-2.7 git: "fatal: unable to look up current user in the passwd file: no such user"
      - GIT_COMMITTER_NAME=Docker
      - GIT_COMMITTER_EMAIL=ex@example.com
    networks:
      base_net:
        ipv4_address: 172.18.241.7

  mysql:
    image: mysql:8.0
    container_name: json-validator-mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mariadb
      - ./docker/mysql/local.cnf:/etc/mysql/conf.d/local.cnf
      - /tmp:/tmp
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: json-validator
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 123
    networks:
      base_net:
        ipv4_address: 172.18.241.10

networks:
  base_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.241.0/24

volumes:
  mysql-data:
  redisdata:
  xhgui-root: {}
